Repository irontec/ivozprovider, pull requests merged in 2018-06, with the labels that each got.

#522 portals: fix extension for CallForwardsettings edit screen
  portals/application/configs/klear/CallForwardSettingsList.yaml
Labels: +bug, web/admin

#519 web/admin: wrap rawConditions in order to avoid filtering errors
  web/admin/application/configs/klear/MatchListsList.yaml
  web/admin/application/configs/klear/TransformationRuleSetsList.yaml
Labels: +bug, web/admin

#520 Peer server orm definition
  library/DataFixtures/ORM/KamTrunksLcrGateway.php
  library/DataFixtures/ORM/ProviderPeerServer.php
  library/Ivoz/Kam/Domain/Model/TrunksLcrGateway/TrunksLcrGatewayAbstract.php
  library/Ivoz/Kam/Domain/Model/TrunksLcrGateway/TrunksLcrGatewayDtoAbstract.php
  library/Ivoz/Kam/Domain/Model/TrunksLcrGateway/TrunksLcrGatewayInterface.php
  library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/TrunksLcrGateway.TrunksLcrGatewayAbstract.orm.yml
  library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerAbstract.php
  library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerDtoAbstract.php
  library/Ivoz/Provider/Domain/Model/PeerServer/PeerServerInterface.php
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Company.CompanyAbstract.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/PeerServer.PeerServerAbstract.orm.yml
  scheme/app/DoctrineMigrations/Version20180606134347.php
  web/rest/features/provider/peerServer/getPeerServer.feature
  web/rest/features/provider/peerServer/postPeerServer.feature
  web/rest/features/provider/peerServer/putPeerServer.feature
Labels: +bug, core

#518 Lcr lifecycle rework
  library/CoreBundle/Resources/config/orm_soft_delete.yml
  library/DataFixtures/ORM/ProviderOutgoingRouting.php
  library/DataFixtures/ORM/ProviderRoutingTag.php
  library/Ivoz/Core/Application/Service/EntityTools.php
  library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php
  library/Ivoz/Kam/Domain/Model/TrunksLcrRuleTarget/TrunksLcrRuleTargetRepository.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrGateway/UpdateByPeerServer.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/CreateByOutgoingRoutingAndRoutingPattern.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByOutgoingRouting.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByOutgoingRoutingBinding.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByRoutingPattern.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByRoutingPatternGroupsRelPattern.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByRoutingTag.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/CreateByOutgoingRouting.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/CreateByOutgoingRoutingBinding.php
  library/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/CreateByPeerServer.php
  library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/TrunksLcrRuleTargetDoctrineRepository.php
  library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRouting.php
  library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingInterface.php
  library/Ivoz/Provider/Domain/Model/OutgoingRouting/OutgoingRoutingRepository.php
  library/Ivoz/Provider/Domain/Service/RoutingPattern/UpdateByBrand.php
  library/Ivoz/Provider/Domain/Service/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPatternLifecycleEventHandlerInterface.php
  library/Ivoz/Provider/Domain/Service/RoutingPatternGroupsRelPattern/RoutingPatternGroupsRelPatternLifecycleServiceCollection.php
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/OutgoingRouting.OutgoingRouting.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/OutgoingRoutingDoctrineRepository.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrGateway/UpdateByPeerServerSpec.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrRule/CreateByOutgoingRoutingAndRoutingPatternSpec.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByOutgoingRoutingSpec.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrRule/UpdateByRoutingPatternSpec.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/CreateByOutgoingRoutingSpec.php
  library/spec/Ivoz/Kam/Domain/Service/TrunksLcrRuleTarget/CreateByPeerServerSpec.php
  web/rest/tests/Provider/OutgoingRouting/OutgoingRoutingLifeCycleTest.php
  web/rest/tests/Provider/RoutingPattern/RoutingPatternLifeCycleTest.php
  web/rest/tests/Provider/RoutingTag/RoutingTagLifeCycleTest.php
Labels: +bug, +enhancement, core, tests

#524 doc: update ChangeLog for 2.3.0 release
  ChangeLog
  README.md
Labels: doc

#540 core: clean up extensions properly on user delete
  library/IvozProvider/Mapper/Sql/Users.php
Labels: +bug, core

#541 core: clean up ivr state on user/extension delete
  library/IvozProvider/Mapper/Sql/Extensions.php
  library/IvozProvider/Mapper/Sql/Users.php
  library/IvozProvider/Model/Raw/Users.php
  scheme/deltas/084-ivr-custom-entries-cascade-constraint.sql
Labels: +bug, core, scheme

#521 Enable http2 protocol
  debian/ivozprovider-profile-portal.postinst
  profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf
Labels: +enhancement, devops

#544 Remove support for rtpproxy media relay sets
  debian/control
  debian/ivozprovider-profile-proxy.postinst
  debian/ivozprovider.postinst
  doc/sphinx/basics/architecture/audio_flow.rst
  doc/sphinx/locale/es/LC_MESSAGES/basics.po
  extra/simple-cdd/package.list
  kamailio/trunks/config/kamailio.cfg
  kamailio/users/config/kamailio.cfg
  library/CoreBundle/Resources/config/orm_target_entities.yml
  library/DataFixtures/ORM/KamRtpproxy.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/Rtpproxy.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyAbstract.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyDto.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyDtoAbstract.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyInterface.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyRepository.php
  library/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxyTrait.php
  library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/Rtpproxy.Rtpproxy.orm.yml
  library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping/Rtpproxy.RtpproxyAbstract.orm.yml
  library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/RtpproxyDoctrineRepository.php
  library/Ivoz/Provider/Domain/Model/MediaRelaySet/MediaRelaySetAbstract.php
  library/Ivoz/Provider/Domain/Model/MediaRelaySet/MediaRelaySetDtoAbstract.php
  library/Ivoz/Provider/Domain/Model/MediaRelaySet/MediaRelaySetInterface.php
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/MediaRelaySet.MediaRelaySetAbstract.orm.yml
  library/spec/Ivoz/Kam/Domain/Model/Rtpproxy/RtpproxySpec.php
  scheme/app/DoctrineMigrations/Version20180619114825.php
  web/admin/application/configs/klear/KamRtpengineList.yaml
  web/admin/application/configs/klear/KamRtpproxyList.yaml
  web/admin/application/configs/klear/MediaRelaySetsList.yaml
  web/admin/application/configs/klear/conf.d/kamRtpproxyHelp.yaml
  web/admin/application/configs/klear/conf.d/mapperList.yaml
  web/admin/application/configs/klear/model/KamRtpengine.yaml
  web/admin/application/configs/klear/model/KamRtpproxy.yaml
  web/admin/application/configs/klear/model/MediaRelaySets.yaml
  web/admin/application/configs/klear/model/WholesaleClients.yaml
  web/admin/application/languages/en_US/en_US.po
  web/admin/application/languages/es_ES/es_ES.po
  web/admin/application/library/IvozProvider/Klear/Filter/WholesaleMediaRelaySets.php
  web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php
  web/rest/features/provider/company/putCompanies.feature
  web/rest/features/provider/mediaRelaySet/getMediaRelaySet.feature
  web/rest/features/provider/mediaRelaySet/postMediaRelaySet.feature
  web/rest/features/provider/mediaRelaySet/putMediaRelaySet.feature
Labels: +feature, core, scheme, tests, trunks, users, web/rest

#548 recordings: update microservice to handle rtpengine-recordings
  library/Ivoz/Provider/Application/Service/Recording/RecordingDtoAssembler.php
  microservices/recordings/app/config/services.yml
  microservices/recordings/src/Recording/Encoder.php
Labels: +enhancement, core, microservices

#552 Automatic invoice number
  library/CoreBundle/Resources/config/orm_target_entities.yml
  library/Ivoz/Core/Application/Service/EntityTools.php
  library/Ivoz/Provider/Domain/Model/Invoice/Invoice.php
  library/Ivoz/Provider/Domain/Model/Invoice/InvoiceAbstract.php
  library/Ivoz/Provider/Domain/Model/Invoice/InvoiceDtoAbstract.php
  library/Ivoz/Provider/Domain/Model/Invoice/InvoiceInterface.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequence.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceAbstract.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceDto.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceDtoAbstract.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceInterface.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceRepository.php
  library/Ivoz/Provider/Domain/Model/InvoiceNumberSequence/InvoiceNumberSequenceTrait.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceScheduler.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerAbstract.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDto.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerDtoAbstract.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerInterface.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerRepository.php
  library/Ivoz/Provider/Domain/Model/InvoiceScheduler/InvoiceSchedulerTrait.php
  library/Ivoz/Provider/Domain/Service/Invoice/CheckValidity.php
  library/Ivoz/Provider/Domain/Service/Invoice/SetInvoiceNumber.php
  library/Ivoz/Provider/Domain/Service/InvoiceNumberSequence/InvoiceNumberSequenceLifecycleEventHandlerInterface.php
  library/Ivoz/Provider/Domain/Service/InvoiceNumberSequence/InvoiceNumberSequenceLifecycleServiceCollection.php
  library/Ivoz/Provider/Domain/Service/InvoiceNumberSequence/NextValGenerator.php
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/InvoiceNumberSequenceDoctrineRepository.php
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/Invoice.InvoiceAbstract.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceNumberSequence.InvoiceNumberSequence.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceNumberSequence.InvoiceNumberSequenceAbstract.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceScheduler.InvoiceScheduler.orm.yml
  library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping/InvoiceScheduler.InvoiceSchedulerAbstract.orm.yml
  scheme/app/DoctrineMigrations/Version20180622091118.php
  web/admin/application/configs/klear/InvoiceNumberSequencesList.yaml
  web/admin/application/configs/klear/InvoicesList.yaml
  web/admin/application/configs/klear/conf.d/mapperList.yaml
  web/admin/application/configs/klear/klear.yaml
  web/admin/application/configs/klear/model/InvoiceNumberSequences.yaml
  web/admin/application/configs/klear/model/Invoices.yaml
  web/admin/application/languages/en_US/en_US.po
  web/admin/application/languages/es_ES/es_ES.po
  web/admin/application/library/IvozProvider/Klear/Options/OptionsCustomizer.php
  web/rest/features/provider/fixedCostsRelInvoice/postFixedCostsRelInvoice.feature
  web/rest/features/provider/fixedCostsRelInvoice/putFixedCostsRelInvoice.feature
Labels: +feature, core, scheme, web/admin

#568 library: fixed email charset header
  asterisk/agi/application/controllers/VoicemailController.php
  asterisk/agi/library/Agi/Action/FaxCallAction.php
  kamailio/recordings/application/controllers/RecordingsController.php
  portals/application/workers/XmlrpcWorker.php
  portals/application/workers/XmlrpcdelayedproxytrunksWorker.php
Labels: +bug, = oasis =, core

#577 doc: updated ChangeLog for 2.4.0
  ChangeLog
  README.md
Labels: +enhancement, = artemis =, doc
