Repository irontec/ivozprovider, pull requests merged in 2022-01, with the labels that each got.

#1693 portals: redirect apache2 logs to journald
  profiles/portal/etc/apache2/sites-available/020-ivozprovider-portals.conf
  profiles/portal/etc/apache2/sites-available/030-ivozprovider-prov.conf
Labels: +enhancement, * artemis *, ci-no-tests

#1697 as: set max call duration to 3 hours
  asterisk/config/dialplan/default.conf
  asterisk/config/extensions.conf
Labels: +enhancement, * artemis *, ci-no-tests

#1695 Disable DQL query cache on DataGateway
  library/composer.lock
Labels: +bug, core, * artemis *

#1699 Retail account access fix
  web/admin/application/configs/klear/RetailAccountsList.yaml
  web/rest/client/config/api/raw/provider.yml
  web/rest/client/features/provider/retailAccount/putRetailAccount.feature
Labels: +bug, web/rest, web/admin, * artemis *
